"use client"
import {useEffect} from "react"
import {SikasApp} from "./sikas-app"
import {supabase} from "@/lib/supabase"

function install(){
 const seen=new WeakSet<Element>();
 const enhance=()=>{document.querySelectorAll('form').forEach(form=>{if(seen.has(form))return;seen.add(form);const text=(form.textContent||'').toLowerCase();
  const cash=form.querySelector('select[name="cash"]') as HTMLSelectElement|null;
  if(cash){['Cash','E-Wallet','Rekening'].forEach((x,i)=>{const v=['__cash','__ewallet','__bank'][i];if(![...cash.options].some(o=>o.value===v))cash.add(new Option(x,v))});if(![...cash.options].some(o=>o.value==='__custom'))cash.add(new Option('+ Tulis custom…','__custom'));cash.addEventListener('change',async()=>{if(cash.value!=='__custom')return;const name=prompt('Nama kas/rekening custom:');if(!name){cash.selectedIndex=0;return}const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)return;const {data:m}=await supabase.from('school_members').select('school_id').eq('user_id',uid).eq('status','active').maybeSingle();if(!m)return;const {data,rowError}=await supabase.from('cash_accounts').insert({school_id:m.school_id,name,type:'custom'}).select('id').single();if(rowError||!data){alert(rowError?.message||'Gagal membuat kas custom');return}cash.add(new Option(name,data.id));cash.value=data.id})}
  if(text.includes('kegiatan / anggaran')){const a=form.querySelector('select[name="activity"]') as HTMLSelectElement|null;if(a){const w=a.parentElement!;const input=document.createElement('input');input.placeholder='Contoh: Kegiatan MPLS';input.className='hotfix-input';w.replaceChild(input,a);const hidden=document.createElement('input');hidden.type='hidden';hidden.name='activity';w.append(hidden);input.addEventListener('change',async()=>{const name=input.value.trim();if(!name){hidden.value='';return}const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)return;const {data:m}=await supabase.from('school_members').select('school_id').eq('user_id',uid).eq('status','active').maybeSingle();if(!m)return;let {data:old}=await supabase.from('activities').select('id').eq('school_id',m.school_id).ilike('name',name).maybeSingle();if(!old){const {data:n}=await supabase.from('activities').insert({school_id:m.school_id,name,code:'AUTO-'+Date.now(),budget:0}).select('id').single();old=n}if(old)hidden.value=old.id})}}
  const cat=form.querySelector('input[name="category"]') as HTMLInputElement|null;if(cat&&!cat.getAttribute('list')){const dl=document.createElement('datalist');dl.id='sikas-category-options';['SPP / Pendidikan','ATK / Perlengkapan','Listrik / Air / Internet','Honor / Insentif','Kegiatan Sekolah','Pemeliharaan','Transportasi','Konsumsi','Penerimaan lain','Lainnya'].forEach(x=>dl.append(new Option(x)));form.append(dl);cat.setAttribute('list',dl.id);cat.placeholder='Pilih atau tulis custom'}
  const amount=form.querySelector('input[name="amount"]') as HTMLInputElement|null;if(amount&&!amount.placeholder)amount.placeholder='Contoh: 150000';
  if(text.includes('tambah siswa')){const c=form.querySelector('select[name="class_id"]') as HTMLSelectElement|null;if(c){const w=c.parentElement!;const input=document.createElement('input');input.placeholder='Contoh: 7A';input.className='hotfix-input';w.replaceChild(input,c);const hidden=document.createElement('input');hidden.type='hidden';hidden.name='class_id';w.append(hidden);input.addEventListener('change',async()=>{const name=input.value.trim();if(!name){hidden.value='';return}const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)return;const {data:m}=await supabase.from('school_members').select('school_id').eq('user_id',uid).eq('status','active').maybeSingle();if(!m)return;let {data:old}=await supabase.from('classes').select('id').eq('school_id',m.school_id).ilike('name',name).maybeSingle();if(!old){const {data:n}=await supabase.from('classes').insert({school_id:m.school_id,name}).select('id').single();old=n}if(old)hidden.value=old.id})}}
  if(text.includes('tambah kegiatan')){const code=form.querySelector('input[name="code"]') as HTMLInputElement|null;if(code){code.value='AUTO-'+Date.now();code.readOnly=true;code.placeholder='Dibuat otomatis'}}
 })};enhance();const mo=new MutationObserver(enhance);mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()}
export default function SikasHotfix(){useEffect(()=>install(),[]);return <SikasApp/>}
