'use client'

import Image from 'next/image'
import {useEffect,useMemo,useRef,useState} from 'react'
import {supabase,type Member,type Student,type Cash,type Tx,type Bill,type School} from '@/lib/supabase'
import {BarChart3,BookOpen,Building2,Download,FileText,GraduationCap,LayoutDashboard,LogOut,Menu,Moon,Plus,ReceiptText,Settings,Sun,Upload,Users,WalletCards,X} from 'lucide-react'
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'

type View='dashboard'|'finance'|'students'|'bills'|'budget'|'reports'|'team'|'settings'|'owner'
type Toast={kind:'ok'|'error';text:string}|null
type ImportedStudent={nis:string;nisn:string;name:string;className:string;guardianName:string;phone:string;line:number}
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0)
const date=()=>new Date().toISOString().slice(0,10)
const number=(prefix:string)=>`${prefix}-${Date.now().toString().slice(-10)}`
const loginEmail=(value:string)=>{const input=value.trim().toLowerCase();if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input))return input;const slug=input.normalize('NFKD').replace(/[^a-z0-9._-]+/g,'-').replace(/^[._-]+|[._-]+$/g,'');return slug?`${slug}@akun.sikaspro.id`:''}
const authProblem=(message:string)=>{if(/invalid login credentials/i.test(message))return'Username atau password salah. Periksa kembali penulisannya.';if(/email not confirmed/i.test(message))return'Akun belum aktif. Hubungi pengelola jika akun dibuat sebelum perbaikan ini.';if(/rate limit|too many/i.test(message))return'Terlalu banyak percobaan. Tunggu beberapa menit lalu coba lagi.';if(/failed to fetch|network/i.test(message))return'Koneksi ke server bermasalah. Periksa internet lalu coba kembali.';return message||'Terjadi masalah yang belum diketahui. Silakan coba lagi.'}

export function SikasApp(){
 const [ready,setReady]=useState(false),[userId,setUserId]=useState<string|null>(null),[member,setMember]=useState<Member|null>(null),[isSuper,setIsSuper]=useState(false),[view,setView]=useState<View>('dashboard'),[toast,setToast]=useState<Toast>(null),[dark,setDark]=useState(()=>typeof window!=='undefined'&&localStorage.theme==='dark'),[menu,setMenu]=useState(false)
 const notify=(text:string,kind:'ok'|'error'='ok')=>{setToast({text,kind});setTimeout(()=>setToast(null),3500)}
 const reload=async(id?:string)=>{const uid=id||userId;if(!uid)return;const [membership,profile]=await Promise.all([supabase.from('school_members').select('school_id,role,status,schools(id,name,npsn,academic_year)').eq('user_id',uid).eq('status','active').limit(1).maybeSingle(),supabase.from('profiles').select('is_super_admin').eq('id',uid).single()]);if(membership.error)notify(membership.error.message,'error');setMember((membership.data as unknown as Member)||null);setIsSuper(Boolean(profile.data?.is_super_admin))}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const id=data.session?.user.id||null;setUserId(id);if(id){void supabase.rpc('mark_active');reload(id).finally(()=>setReady(true))}else setReady(true)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setUserId(s?.user.id||null);if(s?.user.id){void supabase.rpc('mark_active');reload(s.user.id)}else setMember(null)});return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.theme=dark?'dark':'light'},[dark])
 if(!ready)return <Splash/>
 if(!userId)return <Auth onDone={(id)=>{setUserId(id);reload(id)}} notify={notify}/>
 if(isSuper&&!member)return <OwnerApp onLogout={async()=>{await supabase.auth.signOut();setUserId(null);setIsSuper(false)}}/>
 if(!member)return <Onboarding userId={userId} onDone={()=>reload()} notify={notify}/>
 const role=member.role,school=member.schools
 const nav:[View,string,React.ReactNode][]=[['dashboard','Beranda',<LayoutDashboard key="d"/>],['finance','Keuangan',<WalletCards key="f"/>],['students','Siswa',<GraduationCap key="s"/>],['bills','Tagihan',<ReceiptText key="b"/>],['budget','Anggaran',<BarChart3 key="a"/>],['reports','Laporan',<FileText key="r"/>],...(role==='principal'?[['team','Tim Sekolah',<Users key="t"/>] as [View,string,React.ReactNode]]:[]),['settings','Pengaturan',<Settings key="g"/>]]
 const logout=async()=>{if(!confirm('Keluar dari akun di perangkat ini?'))return;await supabase.auth.signOut();setUserId(null);setMember(null)}
 return <div className="app-shell">
  <aside className={menu?'sidebar open':'sidebar'}><button className="close-mobile" onClick={()=>setMenu(false)}><X/></button><Brand compact/><div className="school-pill"><Building2/><span><b>{school.name}</b><small>{role==='principal'?'Kepala Sekolah':'Bendahara / Staf'}</small></span></div><nav>{nav.map(([id,label,icon])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setMenu(false)}}>{icon}<span>{label}</span></button>)}</nav><button className="logout" onClick={logout}><LogOut/>Keluar</button></aside>
  {menu&&<button className="backdrop" aria-label="Tutup menu" onClick={()=>setMenu(false)}/>}<main><header><button className="icon mobile" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{nav.find(n=>n[0]===view)?.[1]}</h1><p>{school.academic_year}</p></div><span className="grow"/><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header>
  <div className="content">{view==='dashboard'&&<Dashboard school={school}/>} {view==='finance'&&<Finance school={school} notify={notify}/>} {view==='students'&&<Students school={school} notify={notify}/>} {view==='bills'&&<Bills school={school} notify={notify}/>} {view==='budget'&&<Budget school={school} notify={notify}/>} {view==='reports'&&<Reports school={school} notify={notify}/>} {view==='team'&&<Team school={school} notify={notify}/>} {view==='settings'&&<SchoolSettings school={school} notify={notify}/>} {view==='owner'&&<Owner/>}</div></main>
  <nav className="bottom-nav">{nav.slice(0,5).map(([id,label,icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{icon}<small>{label}</small></button>)}</nav>{toast&&<div className={`toast ${toast.kind}`}>{toast.text}</div>}
 </div>
}

function Brand({compact=false}:{compact?:boolean}){return <div className={compact?'brand compact':'brand'}><Image src="/logo.jpg" alt="Bantu Beres" width={compact?48:72} height={compact?48:72}/><span><b>Bantu Beres</b><strong>SIKAS Pro</strong>{!compact&&<small>Keuangan Sekolah</small>}</span></div>}
function Splash(){return <div className="center"><Brand/><span className="spinner"/></div>}

function Auth({onDone,notify}:{onDone:(id:string)=>void;notify:(s:string,k?:'ok'|'error')=>void}){
 const [mode,setMode]=useState<'login'|'signup'>('login'),[busy,setBusy]=useState(false),[problem,setProblem]=useState('')
 const changeMode=(next:'login'|'signup')=>{setMode(next);setProblem('')}
 const fail=(message:string)=>{const text=authProblem(message);setProblem(text);notify(text,'error')}
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setProblem('');const fd=new FormData(e.currentTarget),identifier=String(fd.get('identifier')).trim(),password=String(fd.get('password')),email=loginEmail(identifier);try{if(!email)return fail('Username tidak valid. Gunakan minimal 3 huruf atau angka.');if(mode==='signup'){const {data,error}=await supabase.functions.invoke('register-username',{body:{identifier,password,fullName:String(fd.get('full_name'))}});if(error)return fail(error.message);if(!data?.ok)return fail(data?.error||'Akun tidak berhasil dibuat.')}const result=await supabase.auth.signInWithPassword({email,password});if(result.error)return fail(result.error.message);notify(mode==='login'?'Berhasil masuk':'Akun berhasil dibuat dan langsung masuk');onDone(result.data.user.id)}catch(error){fail(error instanceof Error?error.message:'Terjadi masalah saat memproses akun.')}finally{setBusy(false)}}
 return <div className="auth-page"><section className="auth-hero"><Brand/><h1>Keuangan sekolah<br/><em>lebih tertib.</em></h1><p>Transaksi, tagihan, tunggakan, anggaran, kwitansi dan laporan dalam satu tempat yang aman.</p><div className="hero-points"><span>✓ Satu pintu transaksi</span><span>✓ Laporan otomatis</span><span>✓ Nyaman di HP</span></div></section><section className="auth-card"><div className="tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>changeMode('login')}>Masuk</button><button type="button" className={mode==='signup'?'active':''} onClick={()=>changeMode('signup')}>Daftar</button></div><h2>{mode==='login'?'Selamat datang':'Buat akun kepala sekolah'}</h2><p>{mode==='login'?'Masuk menggunakan username dan password.':'Akun langsung aktif dan otomatis menjadi Kepala Sekolah.'}</p><form onSubmit={submit}>{mode==='signup'&&<Field label="Nama lengkap" name="full_name" autoComplete="name" required/>}<Field label="Username" name="identifier" type="text" autoComplete="username" placeholder="Contoh: kepsek01" minLength={3} required/><Field label="Password" name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={8} required/>{problem&&<div className="form-error" role="alert"><b>{mode==='login'?'Tidak bisa masuk':'Tidak bisa membuat akun'}</b><span>{problem}</span></div>}<button className="primary" disabled={busy}>{busy?'Memproses…':mode==='login'?'Masuk':'Buat akun'}</button></form><small className="hint">Username tidak harus berupa email asli. Simpan username dan password untuk login berikutnya.</small></section></div>
}

function Onboarding({onDone,notify}:{userId:string;onDone:()=>void;notify:(s:string,k?:'ok'|'error')=>void}){
 const [busy,setBusy]=useState(false),params=new URLSearchParams(typeof location==='undefined'?'':location.search),invite=params.get('invite')
 const accept=async()=>{setBusy(true);const {error}=await supabase.rpc('accept_invitation',{raw_token:invite});setBusy(false);if(error)return notify(error.message,'error');history.replaceState({},'',location.pathname);notify('Undangan diterima');onDone()}
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('create_school',{school_name:f.get('name'),school_npsn:f.get('npsn'),school_address:f.get('address'),school_city:f.get('city'),year_label:f.get('year')});setBusy(false);if(error)return notify(error.message,'error');notify('Workspace sekolah berhasil dibuat');onDone()}
 return <div className="onboard"><Brand/><div className="onboard-card">{invite?<><span className="eyebrow">UNDANGAN TIM</span><h1>Bergabung sebagai Bendahara/Staf</h1><p>Terima undangan untuk memperoleh akses ke ruang keuangan sekolah.</p><button className="primary" onClick={accept} disabled={busy}>{busy?'Memproses…':'Terima undangan'}</button></>:<><span className="eyebrow">LANGKAH PERTAMA</span><h1>Siapkan workspace sekolah</h1><p>Informasi ini akan digunakan pada dashboard, laporan dan kwitansi.</p><form onSubmit={create}><Field label="Nama sekolah" name="name" required/><div className="two"><Field label="NPSN" name="npsn"/><Field label="Tahun pelajaran" name="year" defaultValue="2026/2027" required/></div><Field label="Alamat" name="address"/><Field label="Kota / Kabupaten" name="city"/><button className="primary" disabled={busy}>{busy?'Membuat…':'Buat workspace sekolah'}</button></form></>}</div></div>
}

function Dashboard({school}:{school:School}){
 const [tx,setTx]=useState<Tx[]>([]),[bills,setBills]=useState<Bill[]>([]),[students,setStudents]=useState(0)
 useEffect(()=>{Promise.all([supabase.from('transactions').select('*').eq('school_id',school.id).eq('status','posted'),supabase.from('bills').select('*').eq('school_id',school.id),supabase.from('students').select('*',{count:'exact',head:true}).eq('school_id',school.id).eq('status','active')]).then(([a,b,c])=>{setTx((a.data||[]) as Tx[]);setBills((b.data||[]) as Bill[]);setStudents(c.count||0)})},[school.id])
 const income=tx.filter(x=>x.kind==='income').reduce((a,b)=>a+Number(b.amount),0),expense=tx.filter(x=>x.kind==='expense').reduce((a,b)=>a+Number(b.amount),0),arrears=bills.reduce((a,b)=>a+Number(b.amount)-Number(b.paid_amount),0)
 const chart=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);const key=d.toISOString().slice(0,7);return{month:d.toLocaleDateString('id-ID',{month:'short'}),masuk:tx.filter(t=>t.tx_date.startsWith(key)&&t.kind==='income').reduce((a,b)=>a+Number(b.amount),0),keluar:tx.filter(t=>t.tx_date.startsWith(key)&&t.kind==='expense').reduce((a,b)=>a+Number(b.amount),0)}}),[tx])
 return <><section className="welcome"><div><span className="eyebrow">RINGKASAN SEKOLAH</span><h2>Selamat datang di SIKAS Pro</h2><p>Pantau keadaan keuangan {school.name} dari satu dashboard.</p></div><span className="period">Data hari ini<br/><b>{new Date().toLocaleDateString('id-ID',{dateStyle:'long'})}</b></span></section><div className="stats"><Stat label="Total pemasukan" value={money(income)} tone="green"/><Stat label="Total pengeluaran" value={money(expense)} tone="red"/><Stat label="Saldo berjalan" value={money(income-expense)} tone="blue"/><Stat label="Total tunggakan" value={money(arrears)} tone="orange"/></div><div className="grid-2"><Card title="Arus kas 6 bulan"><div className="chart"><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="masuk" fill="#2563eb" radius={[5,5,0,0]}/><Bar dataKey="keluar" fill="#f97316" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Kondisi cepat"><div className="quick-list"><p><span>Siswa aktif</span><b>{students}</b></p><p><span>Transaksi tercatat</span><b>{tx.length}</b></p><p><span>Tagihan aktif</span><b>{bills.filter(b=>b.status!=='paid').length}</b></p><p><span>Status kas</span><b className={income-expense>=0?'positive':'negative'}>{income-expense>=0?'Sehat':'Perlu perhatian'}</b></p></div></Card></div></>
}

function Finance({school,notify}:{school:School;notify:(s:string,k?:'ok'|'error')=>void}){
 const [items,setItems]=useState<Tx[]>([]),[cash,setCash]=useState<Cash[]>([]),[activities,setActivities]=useState<{id:string;name:string}[]>([]),[modal,setModal]=useState(false),[kind,setKind]=useState<'income'|'expense'>('income'),[busy,setBusy]=useState(false)
 const load=()=>Promise.all([supabase.from('transactions').select('*').eq('school_id',school.id).order('tx_date',{ascending:false}),supabase.from('cash_accounts').select('*').eq('school_id',school.id),supabase.from('activities').select('id,name').eq('school_id',school.id)]).then(([a,b,c])=>{setItems((a.data||[]) as Tx[]);setCash((b.data||[]) as Cash[]);setActivities(c.data||[])})
 useEffect(()=>{load()},[school.id])
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),proof=f.get('proof') as File;const {data:{user}}=await supabase.auth.getUser();let proof_path:string|null=null;if(proof?.size){proof_path=`${school.id}/${Date.now()}-${proof.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('transaction-proofs').upload(proof_path,proof);if(up.error){setBusy(false);return notify(up.error.message,'error')}}const {error}=await supabase.from('transactions').insert({school_id:school.id,number:number(kind==='income'?'IN':'OUT'),tx_date:f.get('date'),kind,cash_account_id:f.get('cash'),activity_id:f.get('activity')||null,category:f.get('category'),description:f.get('description'),amount:Number(f.get('amount')),proof_path,created_by:user!.id});setBusy(false);if(error)return notify(error.message,'error');notify('Transaksi berhasil disimpan');setModal(false);load()}
 const voidTx=async(id:string)=>{const reason=prompt('Alasan pembatalan transaksi:');if(!reason)return;const {error}=await supabase.from('transactions').update({status:'void',void_reason:reason}).eq('id',id);if(error)return notify(error.message,'error');notify('Transaksi dibatalkan');load()}
 return <><Toolbar title="Buku transaksi" text="Semua pemasukan dan pengeluaran dicatat dari sini."><button className="secondary" onClick={()=>{setKind('expense');setModal(true)}}><Plus/>Pengeluaran</button><button className="primary small" onClick={()=>{setKind('income');setModal(true)}}><Plus/>Pemasukan</button></Toolbar><Card><DataTable headers={['Tanggal','Nomor','Keterangan','Kategori','Jenis','Nominal','Aksi']} rows={items.map(t=>[t.tx_date,t.number,t.description,t.category,<Badge key="b" tone={t.status==='void'?'muted':t.kind==='income'?'green':'red'}>{t.status==='void'?'Batal':t.kind==='income'?'Masuk':'Keluar'}</Badge>,money(Number(t.amount)),t.status==='posted'?<button key="x" className="link danger" onClick={()=>voidTx(t.id)}>Batalkan</button>:'—'])}/></Card>{modal&&<Modal title={kind==='income'?'Catat pemasukan':'Catat pengeluaran'} onClose={()=>setModal(false)}><form onSubmit={save}><div className="two"><Field label="Tanggal" name="date" type="date" defaultValue={date()} required/><label className="field"><span>Kas / rekening</span><select name="cash" required>{cash.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>{kind==='expense'&&<label className="field"><span>Kegiatan / anggaran (opsional)</span><select name="activity"><option value="">Tanpa kegiatan</option>{activities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<Field label="Kategori" name="category" placeholder={kind==='income'?'SPP / Penerimaan lain':'Operasional / Kegiatan'} required/><Field label="Keterangan" name="description" required/><Field label="Nominal" name="amount" type="number" min="1" required/><Field label="Bukti transaksi (opsional, maks. 5 MB)" name="proof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan transaksi'}</button></form></Modal>}</>
}

function Students({school,notify}:{school:School;notify:(s:string,k?:'ok'|'error')=>void}){
 const [items,setItems]=useState<Student[]>([]),[classes,setClasses]=useState<{id:string;name:string}[]>([]),[modal,setModal]=useState(false),[busy,setBusy]=useState(false),[importing,setImporting]=useState(false),[importNote,setImportNote]=useState<{kind:'ok'|'error';text:string}|null>(null)
 const fileRef=useRef<HTMLInputElement>(null)
 const load=()=>Promise.all([supabase.from('students').select('*,classes(name)').eq('school_id',school.id).order('name'),supabase.from('classes').select('*').eq('school_id',school.id).eq('active',true)]).then(([a,b])=>{setItems((a.data||[]) as Student[]);setClasses(b.data||[])})
 useEffect(()=>{load()},[school.id])
 const addClass=async()=>{const name=prompt('Nama kelas baru:');if(!name)return;const {error}=await supabase.from('classes').insert({school_id:school.id,name});if(error)return notify(error.message,'error');notify('Kelas ditambahkan');load()}
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const {error}=await supabase.from('students').insert({school_id:school.id,nis:f.get('nis'),nisn:f.get('nisn')||null,name:f.get('name'),class_id:f.get('class_id')||null,guardian_name:f.get('guardian_name'),guardian_phone:f.get('guardian_phone')});setBusy(false);if(error)return notify(error.message,'error');notify('Siswa ditambahkan');setModal(false);load()}
 const importExcel=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setImporting(true);setImportNote(null);try{
  if(file.size>5*1024*1024)throw new Error('Ukuran file maksimal 5 MB.')
  const XLSX=await import('xlsx'),book=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=book.Sheets['Data Siswa']||book.Sheets[book.SheetNames[0]]
  if(!sheet)throw new Error('File tidak memiliki lembar data.')
  const matrix=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:'',raw:false}),key=(v:unknown)=>String(v??'').trim().toLowerCase().normalize('NFKD').replace(/[^a-z0-9]/g,''),clean=(v:unknown)=>String(v??'').trim()
  const aliases:Record<string,string>={nis:'nis',nisn:'nisn',nama:'name',namalengkap:'name',kelas:'className',wali:'guardianName',namawali:'guardianName',orangtua:'guardianName',nomorwhatsapp:'phone',nowhatsapp:'phone',whatsapp:'phone',nohp:'phone'}
  const headerIndex=matrix.findIndex(row=>Array.isArray(row)&&row.some(v=>key(v)==='nis')&&row.some(v=>['nama','namalengkap'].includes(key(v))))
  if(headerIndex<0)throw new Error('Kolom NIS dan Nama Lengkap tidak ditemukan. Gunakan template yang disediakan.')
  const columns=(matrix[headerIndex]||[]).map(v=>aliases[key(v)]||''),issues:string[]=[],seen=new Set<string>()
  const rows=matrix.slice(headerIndex+1).map((row,i)=>{const record:ImportedStudent={nis:'',nisn:'',name:'',className:'',guardianName:'',phone:'',line:headerIndex+i+2};columns.forEach((name,j)=>{if(name)record[name as keyof Omit<ImportedStudent,'line'>]=clean(row[j])});return record}).filter(r=>r.nis||r.name||r.className||r.guardianName||r.phone)
  if(!rows.length)throw new Error('Tidak ada data siswa untuk diimpor. Isi mulai baris 5 pada template.')
  if(rows.length>1000)throw new Error('Maksimal 1.000 siswa dalam satu kali impor.')
  for(const row of rows){if(!row.nis)issues.push(`Baris ${row.line}: NIS wajib diisi.`);if(!row.name)issues.push(`Baris ${row.line}: Nama Lengkap wajib diisi.`);if(row.nis&&seen.has(row.nis))issues.push(`Baris ${row.line}: NIS ${row.nis} duplikat di file.`);if(row.phone&&!/^(?:0|\+?62)\d{8,13}$/.test(row.phone.replace(/[\s()-]/g,'')))issues.push(`Baris ${row.line}: format WhatsApp tidak valid.`);seen.add(row.nis)}
  if(issues.length)throw new Error(`${issues.slice(0,5).join(' ')}${issues.length>5?` Ada ${issues.length-5} masalah lain.`:''}`)
  const [{data:existing,error:studentError},{data:currentClasses,error:classError}]=await Promise.all([supabase.from('students').select('nis').eq('school_id',school.id),supabase.from('classes').select('id,name').eq('school_id',school.id).eq('active',true)])
  if(studentError||classError)throw studentError||classError
  const existingNis=new Set((existing||[]).map(s=>s.nis)),classMap=new Map((currentClasses||[]).map(c=>[c.name.trim().toLowerCase(),c.id])),newClassNames=[...new Map(rows.filter(r=>r.className&&!classMap.has(r.className.toLowerCase())).map(r=>[r.className.toLowerCase(),r.className])).values()]
  if(newClassNames.length){const {error}=await supabase.from('classes').upsert(newClassNames.map(name=>({school_id:school.id,name})),{onConflict:'school_id,name',ignoreDuplicates:true});if(error)throw error;const {data,error:reloadError}=await supabase.from('classes').select('id,name').eq('school_id',school.id).eq('active',true);if(reloadError)throw reloadError;(data||[]).forEach(c=>classMap.set(c.name.trim().toLowerCase(),c.id))}
  const skipped=rows.filter(r=>existingNis.has(r.nis)).length,payload=rows.filter(r=>!existingNis.has(r.nis)).map(r=>({school_id:school.id,nis:r.nis,nisn:r.nisn||null,name:r.name,class_id:r.className?classMap.get(r.className.toLowerCase())||null:null,guardian_name:r.guardianName||null,guardian_phone:r.phone?.replace(/[\s()-]/g,'')||null}))
  if(!payload.length)throw new Error(`Semua ${skipped} NIS sudah ada. Tidak ada siswa baru yang ditambahkan.`)
  const {error}=await supabase.from('students').insert(payload);if(error)throw error
  const text=`${payload.length} siswa berhasil diimpor${skipped?`; ${skipped} NIS yang sudah ada dilewati.`:'.'}`;setImportNote({kind:'ok',text});notify(`${payload.length} siswa berhasil diimpor`);await load()
 }catch(error){const text=error instanceof Error?error.message:'File tidak dapat diproses.';setImportNote({kind:'error',text});notify('Impor gagal. Lihat keterangan pada halaman.','error')}finally{setImporting(false)}}
 const deactivate=async(id:string)=>{if(!confirm('Nonaktifkan siswa ini? Riwayat keuangan tetap disimpan.'))return;const {error}=await supabase.from('students').update({status:'inactive'}).eq('id',id);if(error)return notify(error.message,'error');notify('Siswa dinonaktifkan');load()}
 return <><Toolbar title="Data siswa" text={`${items.filter(i=>i.status==='active').length} siswa aktif`}><a className="secondary download-link" href="/Template-Import-Siswa-SIKAS-Pro.xlsx" download><Download/>Template Excel</a><button className="secondary" onClick={()=>fileRef.current?.click()} disabled={importing}><Upload/>{importing?'Mengimpor…':'Import Excel'}</button><input ref={fileRef} className="file-input" type="file" accept=".xlsx,.xls" onChange={importExcel}/><button className="secondary" onClick={addClass}><Plus/>Kelas</button><button className="primary small" onClick={()=>setModal(true)}><Plus/>Tambah siswa</button></Toolbar>{importNote&&<div className={`import-note ${importNote.kind}`} role={importNote.kind==='error'?'alert':'status'}><b>{importNote.kind==='error'?'Impor belum berhasil':'Impor selesai'}</b><span>{importNote.text}</span></div>}<Card><DataTable headers={['NIS','NISN','Nama','Kelas','Wali','WhatsApp','Status','Aksi']} rows={items.map(s=>[s.nis,s.nisn||'—',s.name,s.classes?.name||'—',s.guardian_name||'—',s.guardian_phone||'—',<Badge key="s" tone={s.status==='active'?'green':'muted'}>{s.status}</Badge>,s.status==='active'?<button key="x" className="link danger" onClick={()=>deactivate(s.id)}>Nonaktifkan</button>:'—'])}/></Card>{modal&&<Modal title="Tambah siswa" onClose={()=>setModal(false)}><form onSubmit={save}><div className="two"><Field label="NIS" name="nis" required/><Field label="NISN" name="nisn"/></div><label className="field"><span>Kelas</span><select name="class_id"><option value="">Belum ditentukan</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label="Nama lengkap" name="name" required/><Field label="Nama wali" name="guardian_name"/><Field label="Nomor WhatsApp" name="guardian_phone" placeholder="08xxxxxxxxxx"/><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan siswa'}</button></form></Modal>}</>
}

function Bills({school,notify}:{school:School;notify:(s:string,k?:'ok'|'error')=>void}){
 const [items,setItems]=useState<Bill[]>([]),[students,setStudents]=useState<Student[]>([]),[cash,setCash]=useState<Cash[]>([]),[modal,setModal]=useState<'bill'|'pay'|null>(null),[selected,setSelected]=useState<Bill|null>(null),[busy,setBusy]=useState(false)
 const load=()=>Promise.all([supabase.from('bills').select('*,students(name,nis)').eq('school_id',school.id).order('created_at',{ascending:false}),supabase.from('students').select('*').eq('school_id',school.id).eq('status','active'),supabase.from('cash_accounts').select('*').eq('school_id',school.id).eq('active',true)]).then(([a,b,c])=>{setItems((a.data||[]) as Bill[]);setStudents((b.data||[]) as Student[]);setCash((c.data||[]) as Cash[])})
 useEffect(()=>{load()},[school.id])
 const add=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),{data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('bills').insert({school_id:school.id,student_id:f.get('student'),title:f.get('title'),period:f.get('period'),due_date:f.get('due'),amount:Number(f.get('amount')),created_by:user!.id});setBusy(false);if(error)return notify(error.message,'error');notify('Tagihan dibuat');setModal(null);load()}
 const pay=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;setBusy(true);const f=new FormData(e.currentTarget);const {data,error}=await supabase.rpc('record_payment',{target_bill:selected.id,target_cash:f.get('cash'),paid:Number(f.get('amount')),payment_method:f.get('method')});setBusy(false);if(error)return notify(error.message,'error');notify(`Pembayaran berhasil · ${data}`);setModal(null);load()}
 const wa=(b:Bill)=>{const s=students.find(x=>x.id===b.student_id),phone=(s?.guardian_phone||'').replace(/^0/,'62').replace(/\D/g,'');if(!phone)return notify('Nomor WhatsApp wali belum tersedia','error');const remain=Number(b.amount)-Number(b.paid_amount),msg=encodeURIComponent(`Yth. Bapak/Ibu ${s?.guardian_name||'Wali Siswa'}, kami informasikan tagihan ${b.title} atas nama ${s?.name} sebesar ${money(remain)}. Terima kasih.`);window.open(`https://wa.me/${phone}?text=${msg}`,'_blank')}
 return <><Toolbar title="Tagihan siswa" text="Pantau lunas, sebagian, dan tunggakan."><button className="primary small" onClick={()=>setModal('bill')}><Plus/>Buat tagihan</button></Toolbar><Card><DataTable headers={['Siswa','Tagihan','Periode','Jatuh tempo','Nilai','Terbayar','Status','Aksi']} rows={items.map(b=>[b.students?.name||'—',b.title,b.period||'—',b.due_date||'—',money(Number(b.amount)),money(Number(b.paid_amount)),<Badge key="s" tone={b.status==='paid'?'green':b.status==='partial'?'orange':'red'}>{b.status==='paid'?'Lunas':b.status==='partial'?'Sebagian':'Belum bayar'}</Badge>,<span key="a" className="actions">{b.status!=='paid'&&<button className="link" onClick={()=>{setSelected(b);setModal('pay')}}>Bayar</button>}<button className="link" onClick={()=>wa(b)}>WhatsApp</button></span>])}/></Card>{modal==='bill'&&<Modal title="Buat tagihan" onClose={()=>setModal(null)}><form onSubmit={add}><label className="field"><span>Siswa</span><select name="student" required>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.nis}</option>)}</select></label><Field label="Nama tagihan" name="title" placeholder="SPP / Daftar Ulang" required/><div className="two"><Field label="Periode" name="period" type="month"/><Field label="Jatuh tempo" name="due" type="date"/></div><Field label="Nominal" name="amount" type="number" min="1" required/><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Buat tagihan'}</button></form></Modal>}{modal==='pay'&&selected&&<Modal title={`Bayar · ${selected.students?.name}`} onClose={()=>setModal(null)}><form onSubmit={pay}><div className="bill-summary"><span>Sisa tagihan</span><b>{money(Number(selected.amount)-Number(selected.paid_amount))}</b></div><Field label="Nominal pembayaran" name="amount" type="number" min="1" max={Number(selected.amount)-Number(selected.paid_amount)} required/><label className="field"><span>Masuk ke kas</span><select name="cash" required>{cash.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Metode</span><select name="method"><option>Tunai</option><option>Transfer</option><option>QRIS</option></select></label><button className="primary" disabled={busy}>{busy?'Memproses…':'Simpan pembayaran'}</button></form></Modal>}</>
}

function Budget({school,notify}:{school:School;notify:(s:string,k?:'ok'|'error')=>void}){
 const [items,setItems]=useState<{id:string;code:string;name:string;funding_source:string;budget:number}[]>([]),[tx,setTx]=useState<Tx[]>([]),[modal,setModal]=useState(false)
 const load=()=>Promise.all([supabase.from('activities').select('*').eq('school_id',school.id),supabase.from('transactions').select('*').eq('school_id',school.id).eq('kind','expense').eq('status','posted')]).then(([a,b])=>{setItems(a.data||[]);setTx((b.data||[]) as Tx[])})
 useEffect(()=>{load()},[school.id])
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),{error}=await supabase.from('activities').insert({school_id:school.id,code:f.get('code'),name:f.get('name'),funding_source:f.get('source'),budget:Number(f.get('budget'))});if(error)return notify(error.message,'error');notify('Kegiatan dan pagu ditambahkan');setModal(false);load()}
 return <><Toolbar title="Anggaran kegiatan" text="Realisasi dihitung langsung dari pengeluaran."><button className="primary small" onClick={()=>setModal(true)}><Plus/>Tambah kegiatan</button></Toolbar><div className="cards-list">{items.length?items.map(i=>{const used=tx.filter(t=>(t as Tx&{activity_id?:string}).activity_id===i.id).reduce((a,b)=>a+Number(b.amount),0),pct=i.budget?Math.min(100,used/i.budget*100):0;return <Card key={i.id}><div className="budget-head"><div><small>{i.code} · {i.funding_source||'Dana sekolah'}</small><h3>{i.name}</h3></div><Badge tone={used>i.budget?'red':pct>80?'orange':'green'}>{used>i.budget?'Melebihi':pct>80?'Hampir habis':'Aman'}</Badge></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="budget-values"><span>Realisasi <b>{money(used)}</b></span><span>Sisa <b>{money(i.budget-used)}</b></span><span>Pagu <b>{money(i.budget)}</b></span></div></Card>}):<Empty text="Belum ada anggaran kegiatan."/>}</div>{modal&&<Modal title="Tambah kegiatan" onClose={()=>setModal(false)}><form onSubmit={save}><div className="two"><Field label="Kode" name="code" required/><Field label="Sumber dana" name="source"/></div><Field label="Nama kegiatan" name="name" required/><Field label="Pagu" name="budget" type="number" min="0" required/><button className="primary">Simpan kegiatan</button></form></Modal>}</>
}

function Reports({school,notify}:{school:School;notify:(s:string,k?:'ok'|'error')=>void}){
 const [tx,setTx]=useState<Tx[]>([]),[month,setMonth]=useState(new Date().toISOString().slice(0,7))
 useEffect(()=>{supabase.from('transactions').select('*').eq('school_id',school.id).eq('status','posted').order('tx_date').then(({data})=>setTx((data||[]) as Tx[]))},[school.id])
 const rows=tx.filter(t=>t.tx_date.startsWith(month)),income=rows.filter(t=>t.kind==='income').reduce((a,b)=>a+Number(b.amount),0),expense=rows.filter(t=>t.kind==='expense').reduce((a,b)=>a+Number(b.amount),0)
 const pdf=async()=>{void supabase.rpc('track_report',{target_school:school.id});const [{default:jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const doc=new jsPDF();doc.setFontSize(16);doc.text('BUKU KAS UMUM',105,18,{align:'center'});doc.setFontSize(10);doc.text(`${school.name} · Periode ${month}`,105,25,{align:'center'});autoTable(doc,{startY:32,head:[['Tanggal','Nomor','Keterangan','Masuk','Keluar']],body:rows.map(t=>[t.tx_date,t.number,t.description,t.kind==='income'?money(Number(t.amount)):'—',t.kind==='expense'?money(Number(t.amount)):'—']),foot:[['','','TOTAL',money(income),money(expense)]]});doc.save(`BKU-${school.name}-${month}.pdf`);notify('PDF berhasil dibuat')}
 const excel=async()=>{void supabase.rpc('track_report',{target_school:school.id});const XLSX=await import('xlsx');const data=rows.map(t=>({Tanggal:t.tx_date,Nomor:t.number,Keterangan:t.description,Kategori:t.category,Pemasukan:t.kind==='income'?t.amount:0,Pengeluaran:t.kind==='expense'?t.amount:0})),ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'BKU');XLSX.writeFile(wb,`BKU-${school.name}-${month}.xlsx`);notify('Excel berhasil dibuat')}
 return <><Toolbar title="Pusat laporan" text="Preview dan unduhan menggunakan data yang sama."><label className="month"><span>Periode</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></Toolbar><div className="stats"><Stat label="Pemasukan periode" value={money(income)} tone="green"/><Stat label="Pengeluaran periode" value={money(expense)} tone="red"/><Stat label="Surplus / defisit" value={money(income-expense)} tone="blue"/><Stat label="Jumlah transaksi" value={String(rows.length)} tone="orange"/></div><Card title="Preview Buku Kas Umum" actions={<><button className="secondary" onClick={excel}><Download/>Excel</button><button className="primary small" onClick={pdf}><Download/>PDF</button></>}><DataTable headers={['Tanggal','Nomor','Keterangan','Kategori','Pemasukan','Pengeluaran']} rows={rows.map(t=>[t.tx_date,t.number,t.description,t.category,t.kind==='income'?money(Number(t.amount)):'—',t.kind==='expense'?money(Number(t.amount)):'—'])}/></Card></>
}

function Team({school,notify}:{school:School;notify:(s:string,k?:'ok'|'error')=>void}){
 const [members,setMembers]=useState<{user_id:string;role:string;status:string;profiles?:{full_name:string;username:string}}[]>([]),[invites,setInvites]=useState<{id:string;expires_at:string;accepted_at:string|null;revoked_at:string|null}[]>([])
 const load=()=>Promise.all([supabase.from('school_members').select('*,profiles(full_name,username)').eq('school_id',school.id),supabase.from('invitations').select('*').eq('school_id',school.id).order('created_at',{ascending:false})]).then(([a,b])=>{setMembers(a.data||[]);setInvites(b.data||[])})
 useEffect(()=>{load()},[school.id])
 const invite=async()=>{const {data,error}=await supabase.rpc('create_invitation',{target_school:school.id});if(error)return notify(error.message,'error');const url=`${location.origin}/?invite=${data}`;await navigator.clipboard.writeText(url);notify('Link undangan disalin. Berlaku 7 hari.');load()}
 const disable=async(uid:string)=>{if(!confirm('Nonaktifkan anggota ini?'))return;const {error}=await supabase.from('school_members').update({status:'inactive'}).eq('school_id',school.id).eq('user_id',uid);if(error)return notify(error.message,'error');notify('Anggota dinonaktifkan');load()}
 return <><Toolbar title="Tim sekolah" text="Kelola akses Bendahara / Staf Keuangan."><button className="primary small" onClick={invite}><Plus/>Buat link undangan</button></Toolbar><div className="grid-2"><Card title="Anggota"><div className="quick-list">{members.map(m=><p key={m.user_id}><span><b>{m.profiles?.full_name||'Pengguna'}</b><small>@{m.profiles?.username} · {m.role==='principal'?'Kepala Sekolah':'Bendahara/Staf'}</small></span><span><Badge tone={m.status==='active'?'green':'muted'}>{m.status}</Badge>{m.role==='staff'&&m.status==='active'&&<button className="link danger" onClick={()=>disable(m.user_id)}>Nonaktifkan</button>}</span></p>)}</div></Card><Card title="Riwayat undangan"><div className="quick-list">{invites.length?invites.map(i=><p key={i.id}><span>Dibuat untuk Bendahara/Staf<small>Kedaluwarsa {new Date(i.expires_at).toLocaleDateString('id-ID')}</small></span><Badge tone={i.accepted_at?'green':i.revoked_at?'muted':'orange'}>{i.accepted_at?'Diterima':i.revoked_at?'Batal':'Aktif'}</Badge></p>):<Empty text="Belum ada undangan."/>}</div></Card></div></>
}

function SchoolSettings({school,notify}:{school:School;notify:(s:string,k?:'ok'|'error')=>void}){const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),{error}=await supabase.from('schools').update({name:f.get('name'),npsn:f.get('npsn'),academic_year:f.get('year')}).eq('id',school.id);if(error)return notify(error.message,'error');notify('Pengaturan sekolah disimpan')};return <Card title="Profil sekolah"><form className="settings-form" onSubmit={save}><Field label="Nama sekolah" name="name" defaultValue={school.name} required/><div className="two"><Field label="NPSN" name="npsn" defaultValue={school.npsn||''}/><Field label="Tahun pelajaran" name="year" defaultValue={school.academic_year} required/></div><button className="primary">Simpan perubahan</button></form></Card>}
function Owner(){return <Card title="Owner Control"><Empty text="Panel pemilik tersedia pada akun Super Admin khusus."/></Card>}

function OwnerApp({onLogout}:{onLogout:()=>void}){const [schools,setSchools]=useState<(School&{subscriptions?:{status:string;plan:string}|null;usage_metrics?:{students_count:number;transactions_count:number;reports_count:number;storage_bytes:number;last_active_at:string|null}|null})[]>([]),[people,setPeople]=useState<{id:string;full_name:string;username:string;last_seen_at:string|null}[]>([]);useEffect(()=>{Promise.all([supabase.from('schools').select('*,subscriptions(status,plan),usage_metrics(students_count,transactions_count,reports_count,storage_bytes,last_active_at)').order('created_at',{ascending:false}),supabase.from('profiles').select('id,full_name,username,last_seen_at').order('last_seen_at',{ascending:false,nullsFirst:false})]).then(([a,b])=>{setSchools(a.data||[]);setPeople(b.data||[])})},[]);return <div className="owner-page"><header><Brand compact/><span className="grow"/><Badge tone="orange">SUPER ADMIN</Badge><button className="secondary" onClick={onLogout}><LogOut/>Keluar</button></header><main className="content"><Toolbar title="Owner Control" text="Pemantauan produk tanpa membuka data keuangan sekolah."/><div className="stats"><Stat label="Sekolah terdaftar" value={String(schools.length)} tone="blue"/><Stat label="Total pengguna" value={String(people.length)} tone="green"/><Stat label="Sekolah aktif" value={String(schools.filter(s=>s.subscriptions?.status==='active'||s.subscriptions?.status==='trial').length)} tone="orange"/><Stat label="Total penyimpanan" value={`${(schools.reduce((a,s)=>a+Number(s.usage_metrics?.storage_bytes||0),0)/1048576).toFixed(1)} MB`} tone="red"/></div><Card title="Daftar pelanggan"><DataTable headers={['Sekolah','NPSN','Paket','Status','Siswa','Transaksi','Laporan','Aktif terakhir']} rows={schools.map(s=>[s.name,s.npsn||'—',s.subscriptions?.plan||'trial',<Badge key="x" tone="green">{s.subscriptions?.status||'trial'}</Badge>,String(s.usage_metrics?.students_count||0),String(s.usage_metrics?.transactions_count||0),String(s.usage_metrics?.reports_count||0),s.usage_metrics?.last_active_at?new Date(s.usage_metrics.last_active_at).toLocaleString('id-ID'):'—'])}/></Card><Card title="Akses pengguna terbaru"><DataTable headers={['Nama','Username','Terakhir masuk']} rows={people.slice(0,20).map(p=>[p.full_name,`@${p.username}`,p.last_seen_at?new Date(p.last_seen_at).toLocaleString('id-ID'):'Belum tercatat'])}/></Card></main></div>}

function Toolbar({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <div className="toolbar"><div><h2>{title}</h2><p>{text}</p></div><div className="toolbar-actions">{children}</div></div>}
function Stat({label,value,tone}:{label:string;value:string;tone:string}){return <div className={`stat ${tone}`}><small>{label}</small><b>{value}</b></div>}
function Card({title,actions,children}:{title?:string;actions?:React.ReactNode;children:React.ReactNode}){return <section className="card">{title&&<div className="card-title"><h3>{title}</h3><div>{actions}</div></div>}{children}</section>}
function Badge({tone,children}:{tone:string;children:React.ReactNode}){return <span className={`badge ${tone}`}>{children}</span>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const{label,...rest}=props;return <label className="field"><span>{label}</span><input {...rest}/></label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-wrap"><button className="backdrop" onClick={onClose}/><section className="modal"><header><h2>{title}</h2><button className="icon" onClick={onClose}><X/></button></header>{children}</section></div>}
function Empty({text}:{text:string}){return <div className="empty"><BookOpen/><p>{text}</p></div>}
function DataTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return rows.length?<div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} data-label={headers[j]}>{v}</td>)}</tr>)}</tbody></table></div>:<Empty text="Belum ada data untuk ditampilkan."/>}
